# Stage 1: Build the Angular application
FROM node:18 AS build

WORKDIR /app

COPY frontend/magnetaraion-app/package*.json ./
RUN npm install

COPY frontend/magnetaraion-app .

RUN npm run build -- --configuration production

# Stage 2: Serve the application with Nginx
FROM nginx:1.21.3-alpine

COPY --from=build /app/dist/magnetaraion-app/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

USER nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
